spring.data.mongodb.uri=mongodb+srv://pscwrdoexcampuongr_db_user:awTqoX9u5zImOKT3@cluster0.xpkt6xb.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true